### ISSUE TITLE
Errors in compiling Uintah

### ISSUE THREAD

**Issue by MaxZZG** [Uintah/Uintah#12]
I succeed to configuring the Uintah using the following command:

`../src/configure --enable-debug --enable-all-components --with-boost=/usr --enable-wasatch_3p F77=gfortran --with-mpi=/usr/lib/openmpi`

Unfortunately, I failed to compile with these errors:

`../src/CCA/Components/MPMFVM/ESMPM.cc: In member function ‘virtual void Uintah::ESMPM::scheduleInterpESPotentialToPart(Uintah::SchedulerP&, const PatchSet*, const MaterialSubset*, const MaterialSubset*, const MaterialSet*)’:
../src/CCA/Components/MPMFVM/ESMPM.cc:358:28: error: ‘class Uintah::MPMLabel’ has no member named
pESPotential’
   task->computes(d_mpm_lb->pESPotential,     mpm_matls);
../src/CCA/Components/MPMFVM/ESMPM.cc:359:28: error: ‘class Uintah::MPMLabel’ has no member named
pESGradPotential’
   task->computes(d_mpm_lb->pESGradPotential, mpm_matls);
../src/CCA/Components/MPMFVM/ESMPM.cc: In member function ‘virtual void Uintah::ESMPM::interpESPotentialToPart(const Uintah::ProcessorGroup*, const PatchSubset*, const MaterialSubset*, Uintah::DataWarehouse*, Uintah::DataWarehouse*)’:
../src/CCA/Components/MPMFVM/ESMPM.cc:411:59: error: ‘class Uintah::MPMLabel’ has no member named
pESPotential’
       new_dw->allocateAndPut(p_espotential,     d_mpm_lb->pESPotential,     pset);
../src/CCA/Components/MPMFVM/ESMPM.cc:412:59: error: ‘class Uintah::MPMLabel’ has no member named
pESGradPotential’
       new_dw->allocateAndPut(p_esgradpotential, d_mpm_lb->pESGradPotential, pset);
configVars.mk:316: recipe for target 'CCA/Components/MPMFVM/ESMPM.o' failed
make: *** [CCA/Components/MPMFVM/ESMPM.o] Error 1`

It looks like there are variables that are not declared in MPMLabel.h. But I found these variables in AMRMPMLabel.h. I don't know whether it is a program error or my compilation process error. Please tell me how to solve it if you have the same problem.

**Comment by wangdpro** [comment]
您好，邮件已收到，我会尽快与您联系。

**Comment by tharman-git** [comment]
Please describe the physical scenario are you trying to simulate?

**Comment by MaxZZG** [comment]
I recently read the Refs.[1], which completed the material point method to simulate the shell model. I want to simulate cloth using a material point shell model. 

[1] Banerjee B . Shell formulation for the material point method.  2003.

**Comment by tharman-git** [comment]
I recommend you reconfigure using:

`../src/configure --enable-debug --enable-mpm  F77=gfortran --with-mpi=/usr/lib/openmp`

and then execute:  `make reallyclean`  before compiling You don't need to compile all of the components in Uintah, just MPM.

**Comment by MaxZZG** [comment]
Thank you very much for your recommendation, I will try it.

**Comment by MaxZZG** [comment]
It worked! Thank you.

**Comment by TorryZeng** [comment]
I have exactly the same issue as MaxZZG in the compiling process. The pESGradPotential and pESPotential variable cannot found. I want to try the MPMFVM method. How to resolve this issue? Is it due to compiling error or program error?

**Comment by wangdpro** [comment]
您好，邮件已收到，我会尽快与您联系。

**Comment by tharman-git** [comment]
The MPMFVM component is a graduate student's project that has been abandoned, is no longer supported, and will be removed from Uintah at a future date.

**Comment by TorryZeng** [comment]
thanks for prompt response. what about MPMICE model? it needs coupling MPM and ICE models. does it have any caveats in compiling?

**Comment by wangdpro** [comment]
您好，邮件已收到，我会尽快与您联系。
