### ISSUE TITLE
Incorrect usage of hypre memory management functions in hypre solver

### ISSUE THREAD

**Issue by TheGermanGeologist** [Uintah/Uintah#13]
When compiling Uintah (debug), I encounter the following error, and a couple of related errors:
```
../src/CCA/Components/Solvers/AMR/HypreSolvers/HypreSolverFAC.cc: In member function ??virtual void Uintah::HypreSolverFAC::solve()??:
../src/CCA/Components/Solvers/AMR/HypreSolvers/HypreSolverFAC.cc:87:23: error: ??hypre_TAlloc?? was not declared in this scope
   87 |     refinementRatio = hypre_TAlloc(hypre_Index, numLevels);
      |                       ^~~~~~~~~~~~
../src/CCA/Components/Solvers/AMR/HypreSolvers/HypreSolverFAC.cc:149:5: error: ??hypre_TFree?? was not declared in this scope
  149 |     hypre_TFree(pLevel);
      |     ^~~~~~~~~~~
make: *** [configVars.mk:316: CCA/Components/Solvers/AMR/HypreSolvers/HypreSolverFAC.o] Error 1
```
The problem seems to be that the hypre functions hypre_Talloc and hypre_TFree require 3 and 2 arguments, respectively, instead of the 2 and 1 arguments given here. I searched for all references of these functions in the hypre libraries and there are indeed no overloads with less arguments. The last argument should be of the type "hypre_MemoryLocation" wich appears to be a enum, so simply an int? But I don't know what "Location type" would be the correct one so that knowledge is pretty much useless to me.
Anyways, it doesn't work at the moment.
I'm using the latest hypre version (2.24.0)
Yes, the include directory is correctly passed to gcc and hypre itself should be installed correctly.
Have the implementations of these functions changed? Is there a version of hypre that is known to work with this?
If not, what can be done to fix it? I'm not familiar with hypre and way out of my depth here.

Any help is appreciated!

**Comment by wangdpro** [comment]
您好，邮件已收到，我会尽快与您联系。

**Comment by tharman-git** [comment]
We have successfully compiled Uinitah with hypre 2.23.0 and gcc 8.3. Please paste the configure line you're using and describe the physical scenario you'd like to simulate.

**Comment by TheGermanGeologist** [comment]
We moved to a new system, I'll report back when this occurs again.

**Comment by wangdpro** [comment]
您好，邮件已收到，我会尽快与您联系。
