### ISSUE TITLE
Is this error message normal?

### ISSUE THREAD

**Issue by drpengyuhuang** [Uintah/Uintah#23]
Hi all,

I am new to Uintah. Recently I have compiled the Uintah MPM components successfully using '-enable-static'. The MPM simulation can run successfully, but at the end of the simulation, there is always an error message like this:

       Timestep 2835    Time=0.000101016 Next delT=3.63558e-08 Wall Time=953.575   EMA=0.227572    ETC=00:00:00  Memory Use    =213.17 MBs
      Sus: going down successfully
      double free or corruption (!prev)
      [c038:14870] *** Process received signal ***
      [c038:14870] Signal: Aborted (6)
      [c038:14870] Signal code:  (-6)
      [c038:14870] [ 0] /lib64/libpthread.so.0(+0x168c0)[0x155553a5c8c0]
      [c038:14870] [ 1] /lib64/libc.so.6(gsignal+0x10d)[0x15555369bcbb]
      [c038:14870] [ 2] /lib64/libc.so.6(abort+0x177)[0x15555369d355]
      [c038:14870] [ 3] /lib64/libc.so.6(+0x90ae7)[0x1555536e1ae7]
      [c038:14870] [ 4] /lib64/libc.so.6(+0x98b6a)[0x1555536e9b6a]
      [c038:14870] [ 5] /lib64/libc.so.6(+0x9a9fc)[0x1555536eb9fc]
      [c038:14870] [ 6] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0xc12c1a]
      [c038:14870] [ 7] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0xaaa75b]
      [c038:14870] [ 8] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x80f666]
      [c038:14870] [ 9] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x884619]
      [c038:14870] [10] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x884649]
      [c038:14870] [11] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x7fdc46]
      [c038:14870] [12] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x7fdeb9]
      [c038:14870] [13] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0xc3f1ab]
      [c038:14870] [14] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0xc3f39f]
      [c038:14870] [15] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x4fa4f3]
      [c038:14870] [16] /lib64/libc.so.6(+0x4dae9)[0x15555369eae9]
      [c038:14870] [17] /lib64/libc.so.6(+0x4dc7a)[0x15555369ec7a]
      [c038:14870] [18] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0xcdbc19]
      [c038:14870] [19] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x4d2c5b]
      [c038:14870] [20] /lib64/libc.so.6(__libc_start_main+0xef)[0x15555368629d]
      [c038:14870] [21] /scratch1/hua106/uintah/Uintah-master/opt/StandAlone/sus[0x4f845a]
      [c038:14870] *** End of error message ***
      --------------------------------------------------------------------------
      Primary job  terminated normally, but 1 process returned
      a non-zero exit code. Per user-direction, the job has been aborted.
      --------------------------------------------------------------------------
      --------------------------------------------------------------------------
      mpirun noticed that process rank 0 with PID 14870 on node c038 exited on signal 6 (Aborted).

This error only occurred after my simulation was finished (or it completed the required simulation time). So I wonder if this error is normal or if I made some mistake and need to recompile the code? It would be great if you could help me out here. Cheers.

Regards,
Pengyu

**Comment by wangdpro** [comment]
您好，邮件已收到，我会尽快与您联系。

**Comment by wangdpro** [comment]
您好，邮件已收到，我会尽快与您联系。
