### ISSUE TITLE
Unable to find mpmice

### ISSUE THREAD

**Issue by li932** [Uintah/Uintah#27]
@DESKTOP-RJKDKF8:/mnt/e/mpm/Uintah-master/dbg$ ../src/configure --enable-debug --enable-all-components --enable-mpmice --with-boost=/usr/include/boost
configure: error: unrecognized options: --enable-mpmice
Hello professor, may I ask what is the reason for this, I downloaded the latest version，
I also didn't find mpmice in.. /src/configure --help.

**Comment by jinxiaoyan-10** [comment]
Hello, I also didn't find mpmice in.. /src/configure --help.
