### ISSUE TITLE
Unsuccessful Uintah installation

### ISSUE THREAD

**Issue by QuocAnh90** [Uintah/Uintah#3]
Hi,

I cloned the Uintah from github.com/Uintah/Uintah

I configured the source code using this command and succeeded: 

../src/configure '--enable-optimize=-O3 -mfpmath=sse' --enable-mpm --without-fortran --with-mpi-lib=/usr/local/lib/openmpi 
--with-mpi-include=/usr/local/include F77=gfortran

**I got the error when compiling as below. Anyone knows how to fix it.**

rm -f VisIt/interfaces/archiveInterface.o
g++ -fPIC  -Wall -O3 -mfpmath=sse -DNDEBUG  -std=c++11    -I../src/include -I../src -I. -I./include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/petsc -MD  -c ../src/VisIt/interfaces/archiveInterface.cc -o VisIt/interfaces/archiveInterface.o
In file included from ../src/Core/Disclosure/TypeDescription.h:28:0,
                 from ../src/Core/Grid/Variables/GridVariable.h:28,
                 from ../src/Core/Grid/Variables/constGridVariable.h:28,
                 from ../src/CCA/Ports/DataWarehouse.h:30,
                 from ../src/VisIt/interfaces/archiveInterface.cc:39:
../src/Core/Parallel/UintahMPI.h: In function ‘int Uintah::MPI::Impl::tid()’:
../src/Core/Parallel/UintahMPI.h:87:16: error: ‘thread_local’ does not name a type
../src/Core/Parallel/UintahMPI.h:88:10: error: ‘id’ was not declared in this scope
In file included from ../src/Core/DataArchive/DataArchive.h:46:0,
                 from ../src/VisIt/interfaces/archiveInterface.cc:43:
../src/Core/Util/Timers/Timers.hpp: In function ‘int Timers::Impl::tid()’:
../src/Core/Util/Timers/Timers.hpp:274:16: error: ‘thread_local’ does not name a type
../src/Core/Util/Timers/Timers.hpp:275:10: error: ‘id’ was not declared in this scope
make: *** [VisIt/interfaces/archiveInterface.o] Error 1

Quoc-Anh

**Comment by jholmen** [comment]
@QuocAnh90: What version compilers are you using? Would recommend GCC 4.8.1 or greater as Uintah makes use of C++11 features such as the mentioned thread_local.

**Comment by QuocAnh90** [comment]
I used GCC 4.7.2. It used to work for Uintah 1.6. Thanks for your comment, I will update to GCC 4.8.1 and let see!

**Comment by QuocAnh90** [comment]
Hi,

I installed gfortran 8.3. I got an error when configure the source code:

"checking for fortran libraries (other) (required)... not found"

Do you know how to fix it?

Quoc-Anh

**Comment by QuocAnh90** [comment]
Hi,

I just installed GCC 4.8.3 in Debian 10 Buster and got the error below when configuring the code. Do you know how to fix it?

"configure error: Could not find the specified C++ compiler (CC)"

gcc --version: cc (Debian 8.3.0-6) 8.3.0

Quoc Anh

**Comment by jholmen** [comment]
Hi @QuocAnh90,

You may need to be more explicit with your Uintah configuration line.

Below is an example of parameters that can be added to your configure line to indicate which compilers are to be used:

```
../src/configure \
  <options> \
  CC=/usr/lib64/openmpi/bin/mpicc \
  CXX=/usr/lib64/openmpi/bin/mpic++ \
  F77=/usr/lib64/openmpi/bin/mpif77
```

John

**Comment by QuocAnh90** [comment]
Hi John @jholmen,

Thank you, I succeeded in compiling the Uintah (opt) in Debian 10 buster. 
The source code is from Github. sus works.

I tried to build the Visit following the Uintah Installation Guide and got the error:

./build_visit2_12_2 --makeflags -j6 --uintah --alt-uintah-dir /home/NTNU/Uintah/Uintah/opt
Using alternate Uintah directory Uintah not found in /home/NTNU/Uintah/Uintah/opt
Error in build process.

I am pretty sure the directory is correct. Do you know how to fix it?

I hope that this is the last time I bother you.
Quoc-Anh

**Comment by QuocAnh90** [comment]
Dear John @jholmen 

Thank you for your comments, I succeeded to compile the Uintah and Visit. However, when running Visit, I got errors as below. Do you know how to fix it?

```
./visit
Running: gui -dv
Running: viewer -dv -geometry 1548x1173+372+27 -borders 45,10,10,10 -shift 0,37 -preshift 10,8 -defer -host 127.0.0.1 -port 5600
/home/NTNU/Uintah/Visit/3.1.2/visit3.1.2/build/exe/viewer: error while loading shared libraries: libvtksys-8.1.so.1: cannot open shared object file: No such file or directory
```

Quoc-Anh

**Comment by jholmen** [comment]
@QuocAnh90: Welcome! Have yet to work with VisIt but maybe only a matter of installing the missing library on your machine?

**Comment by QuocAnh90** [comment]
Hi John, I solved the problem. Anyway, Thank you so much!

**Comment by jholmen** [comment]
@QuocAnh90: Welcome!
